### ISSUE TITLE
Gzipped help files in older version of vim

### ISSUE THREAD

**Issue by hcgraf** [fidian/hexmode#27] opened 2017-07-14 11:37 UTC
Hi,

it seems that commit 7a1610f introduced an issue with gzipped help-files (actually gzipped files in general).
According to the commit history, it seems that you tried to fix that with later commits.

However, unfortunately it doesn't work in vim 7.2  (redhat 6.5). E.g. `:help :help` causes 
```
Error detected while processing function gzip#read:
line 44:
Error: Could not read uncompressed file
E434: Can't find tag pattern
```
Checking out revision 2793233, everything works fine.

Regards
Hagen

**Comment by fidian** [comment] 2017-07-14 11:52
Thanks for telling me the version of vim, your OS distribution and how to replicate the issue. That will be very helpful for diagnosis.

Are you using the latest version from git? I believe the commit you reference was fixed with commit 6426678. Also, the latest version of git doesn't use hexmode by default any longer, after the discussion in #23. You must either set up filename patterns yourself or use `vim -b`.

I ask this because line 44 currently is a comment and shouldn't produce an error.

**Comment by hcgraf** [comment] 2017-07-14 12:06
Yes, I used 8ea24bcf when I first observed the error.
The error seems to refer to line 44 of the `gzip#read` *function* (which is line 89 of `/usr/share/vim/vim72/autoload/gzip.vim`).
(That line is `echoerr "Error: Could not read uncompressed file"`)

**Comment by fidian** [comment] 2017-07-14 12:35
Interesting. I clearly don't know enough about VimScript yet. This seems to be triggered by this block of code.

        au BufReadPost *
            \ let &l:binary = s:IsBinary() |
            \ if &l:binary |
            \   Hexmode |
            \ endif

If I change `s:IsBinary()` to immediately return 0, it still triggers the error. If I comment out the whole thing, it works. If I change it to BufReadPre it also works. I just don't know what this would affect since there's a comment warning me about changing it to BufReadPre:

    " Gzipped help files show up as binary in (and only in) BufReadPost.

I would love to understand why this bit of code is causing problems with gzip instead of just making a workaround, but I'm unable to wrap my head around what's causing any sort of problem with gzip.

**Comment by chaoren** [comment] 2017-07-14 14:37
I'll take a look.

**Comment by chaoren** [comment] 2017-07-14 23:47
Can't reproduce with v7.2.446.

> it doesn't work in vim 7.2

Please be more specific.
Full output of `vim --version` would help.

**Comment by chaoren** [comment] 2017-07-15 00:01
> If I change s:IsBinary() to immediately return 0, it still triggers the error. If I comment out the whole thing, it works. If I change it to BufReadPre it also works.

Are you also able to reproduce this? How?

> I just don't know what this would affect since there's a comment warning me about changing it to BufReadPre:

You misread the comment. It's only there to tell you that you can't trust the value of `&binary` while going into `BufReadPost` with a gzipped file. I.e., if you set `&binary` to `0` in `BufReadPre`, it'll revert back to `1` in `BufReadPost`.

**Comment by hcgraf** [comment] 2017-07-15 05:52
I can find out the exact patchlevel only on Monday.



>Can't reproduce with v7.2.446.
>
>> it doesn't work in vim 7.2
>
>Please be more specific.

**Comment by hcgraf** [comment] 2017-07-17 06:29
It's 7.2.411, full `vim --version` follows.
```
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Feb 17 2012 10:23:31)
Included patches: 1-411
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+arabic +autocmd -balloon_eval -browse ++builtin_terms +byte_offset +cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
+cryptv +cscope +cursorshape +dialog_con +diff +digraphs -dnd -ebcdic
+emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path +find_in_path
+float +folding -footer +fork() +gettext -hangul_input +iconv +insert_expand
+jumplist +keymap +langmap +libcall +linebreak +lispindent +listcmds +localmap
+menu +mksession +modify_fname +mouse -mouseshape +mouse_dec +mouse_gpm
-mouse_jsbterm +mouse_netterm -mouse_sysmouse +mouse_xterm +multi_byte
+multi_lang -mzscheme -netbeans_intg -osfiletype +path_extra +perl +postscript
+printer +profile +python +quickfix +reltime +rightleft -ruby +scrollbind
+signs +smartindent -sniff +startuptime +statusline -sun_workshop +syntax
+tag_binary +tag_old_static -tag_any_white -tcl +terminfo +termresponse
+textobjects +title -toolbar +user_commands +vertsplit +virtualedit +visual
+visualextra +viminfo +vreplace +wildignore +wildmenu +windows +writebackup
-X11 -xfontset -xim -xsmp -xterm_clipboard -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall  -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64  -D_FORTIFY_SOURCE=1    -D_REENTRANT -D_GNU_SOURCE  -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib64/perl5/CORE  -I/usr/include/python2.6 -pthread
Linking: gcc   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -o vim       -lselinux  -lncurses -lacl -lgpm   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lutil -lc -L/usr/lib64/python2.6/config -lpython2.6 -lutil -lm -Xlinker -export-dynamic
```

**Comment by fidian** [comment] 2017-07-17 13:35
I'm using this version of Vim.

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
    Included patches: 1-1689
    Extra patches: 8.0.0056

> Are you also able to reproduce this? How?

Yes, I `cd ~/.vim/bundle/hexmode/doc` and `gzip hexmode.txt`. From there, a simple `vim hexmode.txt.gz` causes the problem.

**Comment by fidian** [comment] 2017-07-17 20:25
@chaoren and @hcgraf If you two could review and test the patch, I would be most obliged.

**Comment by chaoren** [comment] 2017-07-18 01:20
Weird. I tried out the exact same version with the exact same features, and still cannot reproduce. Either by gzipping help files (and updating tags), then `:h Hexmode`, or with `vim hexmode.txt.gz`. But if @fidian's patch fixes the problem, then I don't need to repro anymore. I'll take a look at the patch.

**Comment by fidian** [comment] 2017-07-18 15:20
Did you try `vim -b hexmode.txt.gz` (including `-b`)?

**Comment by chaoren** [comment] 2017-07-18 16:30
> Did you try `vim -b hexmode.txt.gz` (including `-b`)?

Tried that too (though it should make no difference). Still doesn't reproduce.
I think it might have to do with the order of runtime paths. We're probably loading the hexmode plugin and the gzip plugin in different orders, and mine just happens to work out.

**Closed as completed** 2017-07-19 11:44 UTC
